/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.alberto.tp2.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import local.alberto.tp2.model.Produto;

/**
 *
 * @author Lucas Soares Gomes
 */
public class ListaProdutoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaProdutoView
     */
    public ListaProdutoView() {
        initComponents();
        DefaultListModel listaClientes = new DefaultListModel();
        try{
            ArrayList<Produto> produtos;
//            for(int i=0; i<clientes.size(); i++){
//                listaClientes.add(i, clientes.get(i).getIdPokemon() + " - Nome:" + clientes.get(i).getNome() + " - Altura:" + clientes.get(i).getAltura() + " - Ataque:" + clientes.get(i).getAtk() + " - Defesa:" + clientes.get(i).getDef() + " - HP:" + clientes.get(i).getHp() + " - Peso:" + clientes.get(i).getPeso() + " - Speed de Ataque:" + clientes.get(i).getSpAtk() + " - Speed de Defesa" + clientes.get(i).getSpDef() + " - Speed:" + clientes.get(i).getSpeed());
//            }
            listProdutos.setModel(listaClientes);
            listProdutos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                public void valueChanged(javax.swing.event.ListSelectionEvent evt){
                    javax.swing.JList list = (javax.swing.JList)evt.getSource();
                    //Aqui vai o código, que no seu caso, mostrará o nome em um JLabel.
                    //pega o objeto selecionado na lista
                    String obj = (String) list.getSelectedValue();
                    try {
//                        Controller.pokeVisu(obj.split(" ")[0]);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
                    }
                }
            });
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listProdutos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(listProdutos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 80, 550, 400);

        jLabel1.setText("Produtos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 30, 70, 30);

        setBounds(0, 0, 661, 537);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listProdutos;
    // End of variables declaration//GEN-END:variables
}
