/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.alberto.tp2.view;

/**
 *
 * @author Lucas Soares Gomes
 */
public class ListaVendaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaVendaView
     */
    public ListaVendaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVendas = new javax.swing.JList<>();

        getContentPane().setLayout(null);

        jLabel1.setText("Vendas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 30, 70, 30);

        jScrollPane1.setViewportView(listVendas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 560, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listVendas;
    // End of variables declaration//GEN-END:variables
}
